[package]
name = "poker_wins"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5", features = ["derive"] }
oorandom = "11.1.5"
proptest = "1.8.0"
crossbeam = "0.8"
